-- SQL для Supabase: выполнить ОДИН РАЗ в SQL Editor нового проекта
-- (панель слева: SQL Editor → New query → вставить весь файл → Run)
-- ВНИМАНИЕ: перед запуском замени ПОЧТУ_ВЛАДЕЛЬЦА на свой email в самом низу!

-- ═══ 1. Аккаунты и синхронизация ═══

-- избранное: одна строка = одно объявление одного пользователя
create table if not exists favorites (
  user_id uuid not null references auth.users(id) on delete cascade,
  ad_id  text not null,
  data   jsonb not null,
  updated_at timestamptz default now(),
  primary key (user_id, ad_id)
);

-- настройки: одна строка на пользователя (столбцы, фильтры, тема)
create table if not exists settings (
  user_id uuid not null references auth.users(id) on delete cascade,
  data   jsonb not null,
  updated_at timestamptz default now(),
  primary key (user_id)
);

-- ═══ 2. Панель управления временем ═══

-- профили: кто зарегистрировался (строку создаёт сам пользователь при входе)
create table if not exists profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email  text,
  role   text not null default 'user',      -- 'user' | 'admin'
  created_at timestamptz default now()
);

-- выдачи времени: одна строка = один акт выдачи часов
create table if not exists time_grants (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  valid_until timestamptz not null,         -- до какого момента действует
  hours numeric not null,                   -- сколько часов выдано
  created_by uuid,                          -- кто выдал (админ)
  created_at timestamptz default now()
);

-- защита: каждый видит ТОЛЬКО своё; админ видит и меняет всё
alter table favorites  enable row level security;
alter table settings   enable row level security;
alter table profiles   enable row level security;
alter table time_grants enable row level security;

create policy "своё избранное" on favorites
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "свои настройки" on settings
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- профиль: создать/читать свой может каждый; админ читает все;
-- назначить себе роль админа нельзя (роль меняется только здесь, в SQL)
create policy "свой профиль чтение" on profiles
  for select using (auth.uid() = user_id or exists (select 1 from profiles p where p.user_id = auth.uid() and p.role = 'admin'));
create policy "свой профиль создание" on profiles
  for insert with check (auth.uid() = user_id and coalesce(role,'user') = 'user');
create policy "свой профиль обновление" on profiles
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id and coalesce(role,'user') = 'user');

-- время: своё можно только ЧИТАТЬ; выдавать/забирать может только админ
create policy "своё время чтение" on time_grants
  for select using (auth.uid() = user_id or exists (select 1 from profiles p where p.user_id = auth.uid() and p.role = 'admin'));
create policy "выдача только админом" on time_grants
  for insert with check (exists (select 1 from profiles p where p.user_id = auth.uid() and p.role = 'admin'));
create policy "снятие только админом" on time_grants
  for delete using (exists (select 1 from profiles p where p.user_id = auth.uid() and p.role = 'admin'));

-- ═══ 3. Назначить админа ═══
-- Замени ПОЧТУ_ВЛАДЕЛЬЦА на свой email (тот, которым войдёшь в панель) и выполни.
-- Регистрация по этой почте должна УЖЕ существовать (зайди один раз на сайте).

insert into profiles (user_id, email, role)
select id, email, 'admin' from auth.users where email = 'ПОЧТА_ВЛАДЕЛЬЦА'
on conflict (user_id) do update set role = 'admin';
